create extension if not exists pgcrypto;

create table if not exists public.restaurants (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  subtitle text not null default '',
  address text not null default '',
  phone text not null default '',
  tax_id text not null default '',
  tax_rate numeric(5,2) not null default 10,
  is_open boolean not null default true,
  logo_url text not null default '',
  theme_config jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.restaurant_users (
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'staff' check (role in ('owner', 'manager', 'kitchen', 'staff')),
  created_at timestamptz not null default now(),
  primary key (restaurant_id, user_id)
);

create table if not exists public.restaurant_tables (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  local_id text not null,
  name text not null,
  table_token text not null unique,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (restaurant_id, local_id)
);

create table if not exists public.menu_items (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  local_id text not null,
  category text not null,
  name text not null,
  description text not null default '',
  price numeric(10,2) not null check (price >= 0),
  tags jsonb not null default '[]'::jsonb,
  photo_url text not null default '',
  option_template text not null default 'none',
  sold_out boolean not null default false,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (restaurant_id, local_id)
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  public_token uuid not null default gen_random_uuid() unique,
  local_id text unique,
  restaurant_id uuid not null references public.restaurants(id) on delete restrict,
  table_id uuid not null references public.restaurant_tables(id) on delete restrict,
  order_number bigint generated by default as identity,
  status text not null default 'New' check (status in ('New', 'Preparing', 'Ready', 'Served', 'Paid', 'Cancelled')),
  note text not null default '',
  subtotal numeric(10,2) not null default 0,
  tax numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0,
  created_at timestamptz not null default now(),
  served_at timestamptz,
  closed_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  menu_item_id uuid references public.menu_items(id) on delete set null,
  name_snapshot text not null,
  base_price numeric(10,2) not null default 0,
  unit_price numeric(10,2) not null default 0,
  quantity integer not null check (quantity > 0),
  options jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists restaurant_tables_restaurant_idx on public.restaurant_tables(restaurant_id);
create index if not exists menu_items_restaurant_category_idx on public.menu_items(restaurant_id, category, sort_order);
create index if not exists orders_restaurant_status_created_idx on public.orders(restaurant_id, status, created_at desc);
create index if not exists order_items_order_idx on public.order_items(order_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists restaurants_updated_at on public.restaurants;
create trigger restaurants_updated_at before update on public.restaurants
for each row execute function public.set_updated_at();

drop trigger if exists restaurant_tables_updated_at on public.restaurant_tables;
create trigger restaurant_tables_updated_at before update on public.restaurant_tables
for each row execute function public.set_updated_at();

drop trigger if exists menu_items_updated_at on public.menu_items;
create trigger menu_items_updated_at before update on public.menu_items
for each row execute function public.set_updated_at();

drop trigger if exists orders_updated_at on public.orders;
create trigger orders_updated_at before update on public.orders
for each row execute function public.set_updated_at();

create or replace function public.is_restaurant_staff(target_restaurant uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.restaurant_users
    where restaurant_id = target_restaurant and user_id = auth.uid()
  );
$$;

alter table public.restaurants enable row level security;
alter table public.restaurant_users enable row level security;
alter table public.restaurant_tables enable row level security;
alter table public.menu_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "public read active restaurants" on public.restaurants;
create policy "public read active restaurants" on public.restaurants
for select to anon, authenticated using (is_active);

drop policy if exists "staff manage restaurant" on public.restaurants;
create policy "staff manage restaurant" on public.restaurants
for update to authenticated using (public.is_restaurant_staff(id)) with check (public.is_restaurant_staff(id));

drop policy if exists "users read own restaurant roles" on public.restaurant_users;
create policy "users read own restaurant roles" on public.restaurant_users
for select to authenticated using (user_id = auth.uid());

drop policy if exists "public read active tables" on public.restaurant_tables;
create policy "public read active tables" on public.restaurant_tables
for select to anon, authenticated using (is_active);

drop policy if exists "staff manage tables" on public.restaurant_tables;
create policy "staff manage tables" on public.restaurant_tables
for all to authenticated using (public.is_restaurant_staff(restaurant_id)) with check (public.is_restaurant_staff(restaurant_id));

drop policy if exists "public read active menu" on public.menu_items;
create policy "public read active menu" on public.menu_items
for select to anon, authenticated using (is_active);

drop policy if exists "staff manage menu" on public.menu_items;
create policy "staff manage menu" on public.menu_items
for all to authenticated using (public.is_restaurant_staff(restaurant_id)) with check (public.is_restaurant_staff(restaurant_id));

drop policy if exists "public create orders" on public.orders;
create policy "public create orders" on public.orders
for insert to anon, authenticated with check (
  status = 'New' and exists (
    select 1 from public.restaurant_tables t
    where t.id = table_id and t.restaurant_id = restaurant_id and t.is_active
  )
);

drop policy if exists "staff read orders" on public.orders;
create policy "staff read orders" on public.orders
for select to authenticated using (public.is_restaurant_staff(restaurant_id));

drop policy if exists "staff update orders" on public.orders;
create policy "staff update orders" on public.orders
for update to authenticated using (public.is_restaurant_staff(restaurant_id)) with check (public.is_restaurant_staff(restaurant_id));

create or replace function public.can_append_order_items(target_order uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.orders
    where id = target_order
      and status = 'New'
      and created_at > now() - interval '10 minutes'
  );
$$;

revoke all on function public.can_append_order_items(uuid) from public;
grant execute on function public.can_append_order_items(uuid) to anon, authenticated;

drop policy if exists "public create order items" on public.order_items;
create policy "public create order items" on public.order_items
for insert to anon, authenticated
with check (public.can_append_order_items(order_id));

drop policy if exists "staff read order items" on public.order_items;
create policy "staff read order items" on public.order_items
for select to authenticated using (
  exists (
    select 1 from public.orders o
    where o.id = order_id and public.is_restaurant_staff(o.restaurant_id)
  )
);

insert into public.restaurants (
  id, slug, name, subtitle, address, phone, tax_id, tax_rate, theme_config
) values (
  '11111111-1111-4111-8111-111111111111',
  'sake-street',
  'SAKE STREET',
  'Japanese QR table ordering',
  '116 Curlewis Street, Bondi Beach NSW 2026',
  '',
  '',
  10,
  '{"themePreset":"japaneseIzakaya","primaryColor":"#b21f24","menuLayout":"grid","showPhotos":true}'::jsonb
) on conflict (slug) do update set
  name = excluded.name,
  subtitle = excluded.subtitle,
  address = excluded.address,
  theme_config = excluded.theme_config;

insert into public.restaurant_tables (id, restaurant_id, local_id, name, table_token, sort_order)
values
  ('21111111-1111-4111-8111-111111111111', '11111111-1111-4111-8111-111111111111', 't1', 'Table 1', 'tk_1H8KQ', 1),
  ('22222222-2222-4222-8222-222222222222', '11111111-1111-4111-8111-111111111111', 't2', 'Table 2', 'tk_2V7MA', 2),
  ('26666666-6666-4666-8666-666666666666', '11111111-1111-4111-8111-111111111111', 't6', 'Table 6', 'tk_6P4NZ', 6),
  ('28888888-8888-4888-8888-888888888888', '11111111-1111-4111-8111-111111111111', 't8', 'Patio 8', 'tk_8W2CY', 8)
on conflict (restaurant_id, local_id) do update set
  name = excluded.name,
  table_token = excluded.table_token,
  sort_order = excluded.sort_order;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'orders'
  ) then
    alter publication supabase_realtime add table public.orders;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'order_items'
  ) then
    alter publication supabase_realtime add table public.order_items;
  end if;
end;
$$;

create or replace function public.bootstrap_menu(
  p_restaurant_slug text,
  p_items jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  target_restaurant_id uuid;
  inserted_count integer;
begin
  select id into target_restaurant_id
  from public.restaurants
  where slug = p_restaurant_slug and is_active
  limit 1;

  if target_restaurant_id is null then
    raise exception 'RESTAURANT_NOT_FOUND';
  end if;

  if exists (
    select 1 from public.menu_items
    where restaurant_id = target_restaurant_id
  ) then
    raise exception 'MENU_ALREADY_INITIALIZED';
  end if;

  insert into public.menu_items (
    restaurant_id, local_id, category, name, description, price, tags,
    photo_url, option_template, sold_out, sort_order
  )
  select
    target_restaurant_id,
    item ->> 'id',
    item ->> 'category',
    item ->> 'name',
    coalesce(item ->> 'description', ''),
    (item ->> 'price')::numeric,
    coalesce(item -> 'tags', '[]'::jsonb),
    '',
    coalesce(item ->> 'optionTemplate', 'none'),
    coalesce((item ->> 'soldOut')::boolean, false),
    ordinality::integer
  from jsonb_array_elements(p_items) with ordinality as source(item, ordinality);

  get diagnostics inserted_count = row_count;
  return inserted_count;
end;
$$;

revoke all on function public.bootstrap_menu(text, jsonb) from public;
grant execute on function public.bootstrap_menu(text, jsonb) to anon, authenticated;
